version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: miyu-app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=${DATABASE_URL}
      - TWITTER_API_KEY=${TWITTER_API_KEY}
      - TWITTER_API_SECRET=${TWITTER_API_SECRET}
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - SOLANA_RPC_URL=${SOLANA_RPC_URL}
      - SOLANA_WALLET_PRIVATE_KEY=${SOLANA_WALLET_PRIVATE_KEY}
    depends_on:
      - database
    networks:
      - miyu-network

  database:
    image: postgres:15-alpine
    container_name: miyu-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=miyu
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - miyu-network

  adminer:
    image: adminer:latest
    container_name: miyu-adminer
    ports:
      - "8081:8080"
    depends_on:
      - database
    networks:
      - miyu-network

networks:
  miyu-network:
    driver: bridge

volumes:
  db-data:

